[package]
authors = ["mario <mario-krehl@gmx.de>"]
name = "imag-todo"
version = "0.4.0"

description = "Part of the imag core distribution: imag-todo command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
clap = ">=2.17"
log = "0.3"
toml = "0.4"
toml-query = "^0.3.1"
is-match = "0.1"
version = "2.0.1"

libimagrt    = { version = "0.4.0", path = "../../../lib/core/libimagrt" }
libimagerror = { version = "0.4.0", path = "../../../lib/core/libimagerror" }
libimagtodo  = { version = "0.4.0", path = "../../../lib/domain/libimagtodo" }
