[package]
name = "imag-mail"
version = "0.4.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-notes command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

[dependencies]
clap = ">=2.17"
log = "0.3"
version = "2.0.1"

libimagrt       = { version = "0.4.0", path = "../../../lib/core/libimagrt" }
libimagerror    = { version = "0.4.0", path = "../../../lib/core/libimagerror" }
libimagmail     = { version = "0.4.0", path = "../../../lib/domain/libimagmail" }
libimagutil     = { version = "0.4.0", path = "../../../lib/etc/libimagutil" }
